//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenMachine.Layer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantTrait
    {
        public long PlantTraitId { get; set; }
        public long PlantId { get; set; }
        public long TraitId { get; set; }
        public bool Ressesive { get; set; }
        public bool Dominant { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual Plant Plant1 { get; set; }
        public virtual Trait Trait { get; set; }
    }
}
