//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenMachine.Layer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trait
    {
        public Trait()
        {
            this.PlantTrait = new HashSet<PlantTrait>();
        }
    
        public long TraitId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual ICollection<PlantTrait> PlantTrait { get; set; }
    }
}
